language: python
python:
- '3.7'
services:
- docker

env:
  global:
  - GOLOOP_GIT=https://github.com/icon-project/goloop
  - GOLOOP_GIT_TAG=master
  - secure: E0HzKCyZt52y4rfWooVuWbbnYiwpvmd2WqYagSJqYHt535gNR2zbPTB94U6kxFI+hvavXnxyf48FIs2BZXIuVHOv6l143M48KtaP/ODgGby5WHilgY+PI6QI6DRSieVqZG7XSeaxbExiKj5k9mkWkl70pcMHrLbz01gl11+hLJwF9CyetgPFAdrpLa0IW3wthVJGHRTFAx+z2Ow9diXnFz3Qh9+jGc+3abumtQHpgEXmsHiPoLRznFTcHsItOh6g4Oumz72maSU8hxHGrEQEAq/YPuYDZk+UzErCZCpcpfiSoJs1EmazIhs7ASL2iHfoGGLlbSkypJNk6DVYaUwSWoVLB0Fu1MjbphOH3f0L/+9+sI586xRnY7ucc2AFmiFkV7UlnIsn6Yl0NmNe7iTvSYDVTrWZhhI4H9qihGa2Xedg/G4nfc18A2FY6N0CO4AqoMXKvAYsMwnS+vlqLfwfAEkXaOD4r3bOhWYLtI3ssW/GZXN0hOrwztIBYTUc325XErjRBXA+AdXmj12il/MtcytPIM3w+Ri8O2flBdD+6FMthLogc5XOZTtXfLjujW3AOr2oHPe0rlVJXoufoXAw22877RzkU30xhl1fSQUF5t770Mo5ByrbqLQIsE3RNjCJgGgYROQvFjyRjyhAxx3YgSfgrMBpof5+mMyqsJ4DpH0=
  - secure: Yu15Ho8Sy+NLsxHBVrpybuJ7refmMIiQPfianET+fpbXopfXATO8r4lLRG4wTm0zlTB+VUO/8dKEhgdN72eYm1xOSq/AwdXJpkBoYhCWPt1El8MUlBMgZ3IADvw5aGv4Xe27lsA3nhK+2mXg4Nn1Vz6aBFqkWCG0CW6yyK/8d8YjSc5n8ZyhuPEZgUA0Xb261ylGPyoOiUFQGywBa/idRMaUqXAg+RId7B9HkZBZaZEgEFImOhoL+gi3ykH31ttDBMcJl30cS7A277S1CFlxlQzKM2oA8Caq3D2AmKbwBe30uHlUMu6AcjG/dC794OuoiLIyK1qnPn6tyvdoFY5bzpHMCLw6CvY0IehERk7HlBLYR1nuCxOwjRorlWnz49P9btmP1dFqXQVzZofhYNiSQkUmOyzeaxqlgpDOyxcYESlKa6IA3MidrVAnPw9boT2Q8+pZl1v0gwM1URIVadiZ3+bup9fGGI1rZ8IvZ9K+FNkeQKJAf6BcrX5iUeRsiceBXyzeYbxmp3Yeq1QR3P5l8obWxiCsfUwTDsFG9GTaYPS2bBQizOuXizbEaUAZV0oWilWBHB/0Dr3tsXPeraI2NQeIjmWjKcG2HyfneMooxW6eSUD6iDaqo+PGJ0EmcGq7BpaUI/Yx3JWPkPNyCT7CoaOEuIJUsGfngr3QzRBloSs=
jobs:
  include:
#  - os: linux
#    arch: amd64
#    env: goloop_type="goloop"
  - os: linux
    arch: amd64
    env: goloop_type="gochain-icon"

branches:
  only:
  - main
before_install:
- curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
  && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64
  /usr/local/bin/container-structure-test
- 'scversion="stable" # or "v0.4.7", or "latest" wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz"
  | tar -xJv cp "shellcheck-${scversion}/shellcheck" /usr/local/bin/ shellcheck --version

'
- git clone $GOLOOP_GIT
- export TAG_NAME=$(echo "$GOLOOP_GIT_TAG" | sed 's/v//g')
install:
- cd goloop
- git checkout $GOLOOP_GIT_TAG
- make ${goloop_type}-image
script:
- docker login -u $DOCKER_USER --password-stdin -p $DOCKER_PASS
- docker tag goloop $DOCKER_USER/${goloop_type}:$TAG_NAME
- docker tag goloop $DOCKER_USER/${goloop_type}:latest
- docker push $DOCKER_USER/${goloop_type}:$TAG_NAME
- docker push $DOCKER_USER/${goloop_type}:latest
